#!/usr/bin/env bash
GREENFG="\e[38;5;82m"
REDWEAKFG="\e[38;5;132m"
BBLUEFG="\e[1;38;5;75m"
GBLUEFG="\e[1;38;5;73m"
FOLDERNAMEFG="\e[1;38;5;45m"
ERRORFG="\e[1;38;5;197m"
RESET="\e[0m"
BOLD="\e[1m"
while true do
echo -e "${BBLUEFG}NewOS V2 is in it's 'first' release. You may get some bugs here and there."
sleep 2
echo -e "${GREENFG}Welcome to..."
sleep 2
figlet -f slant NewOS V2
sleep 5 
FILE=./startup
if [ -f "$FILE" ]; then
echo -e "${BBLUEFG}Weclome! What is your name?"
read -r name
echo "${name}" > name.txt
echo -e "${GREENFG}Hello ${name}!"
echo -e "${RESET}Rebooting..."
sleep 5
rm -rf ./startup
continue
else
echo "test"

fi
done