#!/usr/bin/env bash
GREENFG="\e[38;5;82m"
REDWEAKFG="\e[38;5;132m"
BBLUEFG="\e[1;38;5;75m"
GBLUEFG="\e[1;38;5;73m"
FOLDERNAMEFG="\e[1;38;5;45m"
ERRORFG="\e[1;38;5;197m"
RESET="\e[0m"
BOLD="\e[1m"
echo -e "${BBLUEFG}NewOS V2 is in it's 'first' release. You may get some bugs here and there."
sleep 2
echo -e "${GREENFG}Welcome to..."
sleep 2
figlet -f slant NewOS V2
echo "Loading..."
sleep 5 
FILE=./startup
if [ -f "$FILE" ]; then
echo -e "${BBLUEFG}Weclome! What is your name?"
read -r name
echo "${name}" > name.txt
echo -e "${GREENFG}Hello ${name}!"
echo -e "${RESET}Rebooting..."
sleep 5
rm -rf ./startup
bash ./run
fi
while true; do
value="$(<name.txt)"  
echo -e -n "(${GREENFG}${value}${RESET}@${REDWEAKFG}localhost${RESET} ${BBLUEFG}${RESET}) ${BOLD}\$ ${RESET}";
read input
if [ "$input" = 'exit' ]; then
echo -e "${GREENFG} Bye bye ${value}!${RESET}"
sleep 3 
exit 0
elif [ "$input" = 'name' ]; then
echo -e "${GBLUEFG}You want to change your name? (Y/N)"
read -n1 -r namechange
if [ "${namechange}" = 'y' ]; then
echo -e "${GREENFG}Okay, What do you want your name to be?"
read namechangenow
echo "${namechangenow}" > name.txt
echo -e "${GREENFG}Hello ${name}! Rebooting now."
bash ./run

fi
elif [ "$input" = 'help' ]; then
echo -e "${ERRORFG} WIP${RESET}"
else
echo -e "${ERRORFG}Command Not Found!${RESET}"
fi
done
